version: '3.1'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    volumes:
      - data:/var/lib/postgresql/data
      - ./src/test/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  data:
    driver: local