spring:
  application:
    name: @project.name@
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres

    username: postgres
    password: postgres
#    pool:
#      enabled: true
#      max-size: 10
#      initial-size: 5

server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
